name: ci
on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - "*"
jobs:
  ci:
    name: ci
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: ./go.mod
          cache: true
          cache-dependency-path: ./go.sum
      - uses: dominikh/staticcheck-action@672a31696676d1592844bf0164b3bbfd855a4d50 # v1.4.1
        with:
          version: "2026.2rc1"
          install-go: false
      - run: go version
      - run: go fmt .
      - run: go build -v .
