name: release
on:
  push:
    tags: "*"

jobs:
  release:
    name: release
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ./go.mod
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=version::$VERSION
          echo "Version $VERSION"
      - run: go install github.com/tcnksm/ghr@latest
      - run: |
          GOOS=linux GOARCH=amd64 go build -o dist/ayame_linux_amd64 cmd/ayame/main.go
          GOOS=linux GOARCH=arm64 go build -o dist/ayame_linux_arm64 cmd/ayame/main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/ayame_darwin_amd64 cmd/ayame/main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/ayame_darwin_arm64 cmd/ayame/main.go
          gzip dist/*
      - run: ghr -t "${{ secrets.GITHUB_TOKEN }}" -u "${{ github.repository_owner }}" -r "ayame" --replace "${{ steps.version.outputs.version }}" dist/
